sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  - py.test --cov cep tests/tests.py
after_success:
  - coveralls
